CREATE TYPE "order_status" AS ENUM (
  'pending',
  'processing',
  'shipped',
  'delivered',
  'cancelled'
);

CREATE TYPE "discount_type" AS ENUM (
  'percentage',
  'fixed'
);

CREATE TYPE "attribute_data_type" AS ENUM (
  'string',
  'integer',
  'decimal',
  'boolean'
);

CREATE TYPE "voucher_type" AS ENUM (
  'fixed_amount',
  'percentage'
);

CREATE TYPE "payment_method" AS ENUM (
  'cod',
  'online'
);

CREATE TYPE "payment_status" AS ENUM (
  'pending',
  'completed',
  'failed'
);

CREATE TYPE "order_source" AS ENUM (
  'online',
  'offline'
);

CREATE TYPE "stock_movement_type" AS ENUM (
  'import',
  'export',
  'adjustment'
);

CREATE TYPE "user_role" AS ENUM (
  'admin',
  'staff',
  'customer'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "role" user_role NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "street" varchar(255) NOT NULL,
  "city" varchar(100) NOT NULL,
  "country" varchar(100) NOT NULL,
  "postal_code" varchar(20),
  "is_default" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "parent_category_id" int,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "brands" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "category_id" int,
  "brand_id" int,
  "image_url" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "product_variations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variation_name" varchar(255),
  "product_id" int NOT NULL,
  "price" decimal(10,2) NOT NULL,
  "sku" varchar(255) UNIQUE,
  "image_url" JSON,
  "quantity" int NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "attributes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) UNIQUE NOT NULL,
  "data_type" attribute_data_type NOT NULL
);

CREATE TABLE "variation_attributes" (
  "product_variation_id" int NOT NULL,
  "attribute_id" int NOT NULL,
  "value" text NOT NULL,
  PRIMARY KEY ("product_variation_id", "attribute_id")
);

CREATE TABLE "product_attributes" (
  "product_id" int NOT NULL,
  "attribute_id" int NOT NULL,
  "value" text NOT NULL,
  PRIMARY KEY ("product_id", "attribute_id")
);

CREATE TABLE "stock_history" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_variation_id" int NOT NULL,
  "quantity" int NOT NULL,
  "type" stock_movement_type NOT NULL,
  "created_at" timestamp,
  "reason" varchar(255)
);

CREATE TABLE "cart_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_variation_id" int NOT NULL,
  "quantity" int NOT NULL,
  "added_at" timestamp
);

CREATE TABLE "orders" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "shipping_address" text,
  "order_date" timestamp NOT NULL,
  "status" order_status NOT NULL,
  "order_source" order_source NOT NULL,
  "total_amount" decimal(10,2) NOT NULL,
  "created_at" timestamp
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "product_variation_id" int NOT NULL,
  "quantity" int NOT NULL,
  "price_per_unit" decimal(10,2) NOT NULL,
  "discount_amount" decimal(10,2) DEFAULT 0
);

CREATE TABLE "product_promotions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_variation_id" int NOT NULL,
  "discount_type" discount_type NOT NULL,
  "discount_value" decimal(10,2) NOT NULL,
  "start_date" timestamp NOT NULL,
  "end_date" timestamp NOT NULL,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "vouchers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE NOT NULL,
  "voucher_type" voucher_type NOT NULL,
  "value" decimal(10,2) NOT NULL,
  "min_order_amount" decimal(10,2) NOT NULL DEFAULT 0,
  "usage_limit" int NOT NULL,
  "valid_from" timestamp NOT NULL,
  "valid_until" timestamp NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "delete_at" timestamp
);

CREATE TABLE "user_vouchers" (
  "user_id" int NOT NULL,
  "voucher_id" int NOT NULL,
  "used_at" timestamp NOT NULL,
  PRIMARY KEY ("user_id", "voucher_id")
);

CREATE TABLE "payments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int UNIQUE NOT NULL,
  "payment_method" payment_method NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "status" payment_status NOT NULL,
  "transaction_id" varchar(255),
  "created_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "product_id" int NOT NULL,
  "rating" int NOT NULL,
  "comment" text,
  "created_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "message" text NOT NULL,
  "created_at" timestamp,
  "deleted_at" timestamp
);

CREATE INDEX ON "categories" ("parent_category_id");

CREATE UNIQUE INDEX ON "cart_items" ("user_id", "product_variation_id");

COMMENT ON TABLE "stock_history" IS 'Lưu lịch sử nhập/xuất kho';

COMMENT ON TABLE "orders" IS 'Thêm trường order_source để phân biệt đơn online/offline';

ALTER TABLE "addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_category_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "products" ADD FOREIGN KEY ("brand_id") REFERENCES "brands" ("id");

ALTER TABLE "product_variations" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "variation_attributes" ADD FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("id");

ALTER TABLE "variation_attributes" ADD FOREIGN KEY ("attribute_id") REFERENCES "attributes" ("id");

ALTER TABLE "product_attributes" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "product_attributes" ADD FOREIGN KEY ("attribute_id") REFERENCES "attributes" ("id");

ALTER TABLE "stock_history" ADD FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("id");

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id");

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("id");

ALTER TABLE "product_promotions" ADD FOREIGN KEY ("product_variation_id") REFERENCES "product_variations" ("id");

ALTER TABLE "user_vouchers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_vouchers" ADD FOREIGN KEY ("voucher_id") REFERENCES "vouchers" ("id");

CREATE TABLE "orders_payments" (
  "orders_id" int,
  "payments_order_id" int,
  PRIMARY KEY ("orders_id", "payments_order_id")
);

ALTER TABLE "orders_payments" ADD FOREIGN KEY ("orders_id") REFERENCES "orders" ("id");

ALTER TABLE "orders_payments" ADD FOREIGN KEY ("payments_order_id") REFERENCES "payments" ("order_id");


ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id");

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
